name: compression
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - bbmap
 - lbzip2
 - libbsc
 - lz4-c
 - perl-biox-seq
 - perl-text-csv
 - pigz
 - sra-tools
 - time
 - xz
 - zstd<=1.3.3
