= Optimal compression scheme to balance ratio and decompression speed
Jeremy Volkening
:source-highlighter: pygments

[abstract]
.Abstract
Some resources spent most of their time in storage but also require quick access when needed.
For these resources, compression speed is of little importance, as they are write-once-read-often objects.
We tested a number of popular compression tools to look for one which provided fast decompression with reasonable file sizes.

== Methods

A variety of paired-end Illumina FASTQ datasets were used as input (TODO: finish description).

=== Software versions

[%header,cols="2*^",format=tsv]
|===
include::versions.tsv[]
|===

== Results


=== Compression ratio


.Compression ratio (higher is better)
image::figure/fig_ratios-1.svg[Compression ratio (higher is better),align=center]



.Ratio of compressed files with Q8 binning (unbinned:binned, higher is better)
image::figure/fig_ratios_q8-1.svg[Ratio of compressed files with Q8 binning (unbinned:binned, higher is better),align=center]


=== (De)compression speed


.Compression rate (MB/s) (higher is better)
image::figure/fig_ctime-1.svg[Compression rate (MB/s) (higher is better),align=center]



.Decompression rate (MB/s) (higher is better)
image::figure/fig_dtime-1.svg[Decompression rate (MB/s) (higher is better),align=center]


=== Memory usage


.Compression maximum resident memory
image::figure/fig_cmem-1.svg[Compression maximum resident memory,align=center]



.Decompression maximum resident memory
image::figure/fig_dmem-1.svg[Decompression maximum resident memory,align=center]


=== CPU usage


.Compression average CPU utilization
image::figure/fig_ccpu-1.svg[Compression average CPU utilization,align=center]



.Decompression average CPU utilization
image::figure/fig_dcpu-1.svg[Decompression average CPU utilization,align=center]

